import "package:cloud_firestore/cloud_firestore.dart";
import "package:firebase_auth/firebase_auth.dart";
import "package:flutter/material.dart";
import "package:lingoneer_beta_0_0_1/components/my_button.dart";
import "package:lingoneer_beta_0_0_1/components/my_textfield.dart";
import "package:lingoneer_beta_0_0_1/pages/home_page.dart";
import "package:lingoneer_beta_0_0_1/pages/login_page.dart";
import "package:lingoneer_beta_0_0_1/services/language_provider.dart";
import "package:provider/provider.dart";

class RegisterPage extends StatefulWidget {
  final void Function()? onTap;

  const RegisterPage({super.key, required this.onTap});

  @override
  State<RegisterPage> createState() => _RegisterPageState();
}

class _RegisterPageState extends State<RegisterPage> {
  final _auth = FirebaseAuth.instance;
  // text editing controllers
  final TextEditingController emailController = TextEditingController();
  final TextEditingController passwordController = TextEditingController();
  final TextEditingController confirmPasswordController =
      TextEditingController();

  // login method
  void signup(BuildContext context) async {
    LanguageProvider languageProvider =
        Provider.of<LanguageProvider>(context, listen: false);

    if (passwordController.text == confirmPasswordController.text) {
      try {
        final user = await _auth.createUserWithEmailAndPassword(
          email: emailController.text.trim(),
          password: passwordController.text,
        );

        // ignore: unnecessary_null_comparison
        if (user != null) {
          await FirebaseFirestore.instance
              .collection('Users')
              .doc(user.user!
                  .uid) // Assuming 'uid' is the user ID generated by Firebase
              .set({
            'userId': user.user!.uid,
            'email': user.user!.email,
            'language': languageProvider.languageComb
          }); // Add the email to Firestore

          // navigate to home page
          Navigator.push(
            context,
            MaterialPageRoute(builder: (context) => const HomePage()),
          );
        }
      } catch (e) {
        String message = "Sign Up failed";
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text(message),
            backgroundColor: Theme.of(context).errorColor,
          ),
        );
      }
    } else {
      String message = "Password not matching";
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text(message),
          backgroundColor: Theme.of(context).errorColor,
        ),
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Theme.of(context).colorScheme.surface,
      body: SingleChildScrollView(
        child: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
          
              // message, app slogan
              Padding(
                padding: const EdgeInsets.only(top: 160),
                child: Text(
                  "Register",
                  style: TextStyle(
                    fontSize: 24,
                    fontWeight: FontWeight.bold,
                    color: Theme.of(context).colorScheme.inversePrimary,
                  ),
                ),
              ),
          
              const SizedBox(height: 15),
          
              // email textfield
              MyTextField(
                  controller: emailController,
                  hintText: "Email",
                  obscureText: false),
          
              const SizedBox(height: 15),
          
              // password textfield
              MyTextField(
                  controller: passwordController,
                  hintText: "Password",
                  obscureText: true),
          
              const SizedBox(height: 15),
          
              // password textfield
              MyTextField(
                  controller: confirmPasswordController,
                  hintText: "Confirm password",
                  obscureText: true),
          
              const SizedBox(height: 15),
          
              // sign up button
              MyButton(
                text: "Sign up",
                onTap: () => signup(context),
              ),
              
              const SizedBox(height: 15),
          
              // already have an account? login here
              Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  Text(
                    "Already have an account?",
                    style: TextStyle(
                      color: Theme.of(context).colorScheme.inversePrimary,
                    ),
                  ),
                  const SizedBox(width: 4),
                  GestureDetector(
                    onTap: () {
                      // Navigate to the registration screen
                      Navigator.push(
                        context, // Current build context
                        MaterialPageRoute(
                            builder: (context) => const LoginPage(
                                  onTap: null,
                                )), // Route definition
                      );
                    },
                    child: Text(
                      "login now",
                      style: TextStyle(
                        color: Theme.of(context).colorScheme.inversePrimary,
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                  )
                ],
              ),

              const SizedBox(height: 25),
          
              // Add a divider
              Divider(
                color: Theme.of(context).colorScheme.inversePrimary,
                thickness: 1, // Adjust thickness as needed
                indent: 16, // Adjust indentation as needed
                endIndent: 16, // Adjust end indentation as needed
              ),
          
              const SizedBox(height: 25),
          
              // sign up button
              const MyButton(
                text: "Google sign up",
                onTap: null,
              ),
            ],
          ),
        ),
      ),
    );
  }
}
