// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGyhyiWMoYIZ2PVXXF0qDPu5ebxkgKg0s',
    appId: '1:568524708573:ios:4a1d872ea2282bcdd7d934',
    messagingSenderId: '568524708573',
    projectId: 'lingoengineer-6f316',
    storageBucket: 'lingoengineer-6f316.appspot.com',
    iosBundleId: 'com.example.lingoneerBeta001',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjmVMS3_rJkGtzBAz4k9wrIOEG2z_gW6I',
    appId: '1:568524708573:web:ef0523bf405788d3d7d934',
    messagingSenderId: '568524708573',
    projectId: 'lingoengineer-6f316',
    authDomain: 'lingoengineer-6f316.firebaseapp.com',
    storageBucket: 'lingoengineer-6f316.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjmVMS3_rJkGtzBAz4k9wrIOEG2z_gW6I',
    appId: '1:568524708573:web:ef0523bf405788d3d7d934',
    messagingSenderId: '568524708573',
    projectId: 'lingoengineer-6f316',
    authDomain: 'lingoengineer-6f316.firebaseapp.com',
    storageBucket: 'lingoengineer-6f316.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGyhyiWMoYIZ2PVXXF0qDPu5ebxkgKg0s',
    appId: '1:568524708573:ios:4a1d872ea2282bcdd7d934',
    messagingSenderId: '568524708573',
    projectId: 'lingoengineer-6f316',
    storageBucket: 'lingoengineer-6f316.appspot.com',
    iosBundleId: 'com.example.lingoneerBeta001',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpwHFAGiNrkuL1Lt3QB_aZEG6n8kNODSs',
    appId: '1:568524708573:android:c0c250ec9722e7bad7d934',
    messagingSenderId: '568524708573',
    projectId: 'lingoengineer-6f316',
    storageBucket: 'lingoengineer-6f316.appspot.com',
  );

}